CREATE DATABASE biblioteca_juss;
\c biblioteca_juss;

CREATE TABLE autores (
    id_autor SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    nacionalidade VARCHAR(100)
);

CREATE TABLE livros (
    id_livro SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    ano_publicacao INT NOT NULL,
    id_autor INT,
    FOREIGN KEY (id_autor) REFERENCES autores(id_autor)
);

INSERT INTO autores (nome, nacionalidade) VALUES
('Ilana Casoy', 'Brasileira'),
('Jeneva Rose', 'Americana'),
(' Roy Wenzl', 'Americano'),
('Raphael Montes', 'Brasileiro'),
('Andrea Killmore', 'Brasileira'),
('Clarice Lispector', 'Brasileira'),
('Robert Galbraith', 'Britânico'),
('Patricia Cornwell', 'Americana'),
('Jo Nesbø', 'Norueguês'),
('Tana French', 'Irlandesa'),
('Donato Carrisi', 'Italiano'),
('Lars Kepler', 'Sueco'),
('J.D. Barker', 'Americano'),
('Angela Marsons', 'Britânica'),
('Camilla Läckberg', 'Sueca'),
('B.A. Paris', 'Britânica'),
('Paula Hawkins', 'Britânica'),
('Leandro Luzone', 'Brasileiro'),
('Felipe Demier', 'Brasileiro'),
('Karin Slaughter', 'Americana'),
('Linwood Barclay', 'Canadense'),
('Jean-Christophe Grangé', 'Francês'),
('Samuel Wainer Filho', 'Brasileiro'),
('Rodrigo Alvarez', 'Brasileiro'),
('Danilo Gentili', 'Brasileiro'),
('Marcelo Rubens Paiva', 'Brasileiro'),
('Antônio Xerxenesky', 'Brasileiro'),
('Edney Silvestre', 'Brasileiro'),
('Ilson Bressan', 'Brasileiro'),
('Cristina Judar', 'Brasileira'),
('Mário Prata', 'Brasileiro'),
('Reinaldo Moraes', 'Brasileiro'),
('Giuliano da Empoli', 'Italiano'),
('Val McDermid', 'Britânica'),
('Peter Swanson', 'Americano'),
('Greer Hendricks', 'Americana'),
('Sarah Pekkanen', 'Americana'),
('Shari Lapena', 'Canadense'),
('Nicci French', 'Britânico'),
('Alice Feeney', 'Britânica'),
('Alex Michaelides', 'Britânico'),
('Louise Candlish', 'Britânica'),
('Caroline Kepnes', 'Americana'),
('Lisa Jewell', 'Britânica'),
('Megan Miranda', 'Americana'),
('Harlan Coben', 'Americano'),
('C.J. Tudor', 'Britânica'),
('Thomas Harris', 'Americano'),
('Charlie Donlea', 'Americano'),
('Jennifer Hillier', 'Canadense'),
('Alafair Burke', 'Americana');


INSERT INTO livros (titulo, ano_publicacao, id_autor) VALUES
('Casos De Família - Arquivos Richthofen E Arquivos Nardoni', 2016, 1),
('Casamento Perfeito ', 2024, 2),
('BTK Profile: Máscara da Maldade', 2019, 3);
('Bom Dia, Verônica', 2016, 4),
('Dias Perfeitos', 2015, 5),
('A Hora da Estrela (Edição Especial Criminal)', 2017, 6),
('Branco Letal', 2018, 7),
('Autópsia', 2021, 8),
('A Sede', 2017, 9),
('O Segredo do Pântano', 2015, 10),
('O Tribunal das Almas', 2016, 11),
('O Caçador de Sonhos', 2019, 12),
('O Quinto Paraíso', 2020, 13),
('Um Corpo na Neve', 2016, 14),
('A Gaiola de Ouro', 2019, 15),
('Entre Quatro Paredes', 2017, 16),
('A Garota no Trem', 2015, 17),
('O Mistério de Boa Esperança', 2022, 18),
('O Dossiê das Sombras', 2020, 19),
('Esposa Perfeita', 2016, 20),
('Elevador 16', 2018, 21),
('O Passageiro das Trevas', 2015, 22),
('Crime em Família', 2019, 23),
('Os Segredos do Vaticano', 2021, 24),
('Como se Tornar o Pior Aluno da Escola (versão criminal)', 2015, 25),
('Malasartes e o Mistério do Assassinato', 2016, 26),
('F.', 2020, 27),
('Se Eu Fechar os Olhos Agora', 2016, 28),
('O Silêncio da Noite', 2022, 29),
('Quarto de Despejo 2: Vidas Interrompidas', 2017, 30),
('Sete Crimes e um Destino', 2021, 31),
('O Cheiro do Ralo 2 - Crime e Delírio', 2020, 32),
('Os Engenheiros do Caos', 2019, 33),
('Insânia', 2016, 34),
('O Tipo Certo de Estranho', 2015, 35),
('A Esposa Entre Nós', 2018, 36),
('Uma Mulher na Escuridão', 2019, 37),
('O Casal que Mora ao Lado', 2016, 38),
('O Dia do Acerto de Contas', 2022, 39),
('Às Cegas', 2018, 40),
('A Paciente Silenciosa', 2019, 41),
('Um Crime na Vizinhança', 2021, 42),
('Você', 2016, 43),
('Depois Daquela Festa', 2020, 44),
('A Última Casa da Rua', 2021, 45),
('Confie em Mim', 2015, 46),
('O Homem de Giz', 2018, 47),
('Cari Mora', 2019, 48),
('A Garota do Lago', 2017, 49),
('Jar of Hearts', 2018, 50),
('A Mulher Errada', 2019, 51);